<?php


return [
    "site_name" => "Teks Global Nigeria",
    "site_title"   => "Teks global Nigeria Investment",
    "company_name" => "Teks Global and Value Chain Services Limited",
    "contact_email" => "nigeria@teksglobal.org",
    "contact_number" => "+237671731827",
    "app_contact" => "admin@teksglobal.org",
    "address" => "Uyo, Akwaibom State, Nigeria",
    "disqus" => "teksadmin",
    "chat_code" => "5a25377bd0795768aaf8d39c",
    "minimum_deposit" => 400.00,
    "minimum_withdraw" => 1000.00,
    "self_transfer" => 2.00,
    "other_transfer" => 2.00,
    "signup_bonus" => 0.00,
    "link_share" => 0.00,
    "referral_signup" => 0.00,
    "referral_deposit" => 1.00,
    "referral_advert" => 0.00,
    "referral_upgrade" => 1.00,
    "ptc" => false,
    "membership_upgrade" => false,
    "ppv" => false,
    "payment_proof" => false,
    "latest_deposit" => false,
    "transfer" => false,
    "invest" => false,
    "live_chat" => false,
];
